	
	upstream backend_servers {
		server 127.0.0.1:8081;
		server 127.0.0.1:8082;
		server 127.0.0.1:8083;
	}
server {
	listen 80;
	server_name localhost;

	location / {
		proxy_pass http://backend_servers;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		add_header Cache-Control "no-cache, no-store, must-revalidate";
	}
		# STATUS MONITORING ENDPOINT
	location /status {
		stub_status on;
		allow 127.0.0.1;
		deny all;
	}
	#HEALTH CHECK ENDPOINT
	location /health {
		return 200 "Load Balancer OK\n";
		add_header Content-Type text/plain;
	}
}
